# requires rustfmt >= 2.0/nightly (for struct_lit_width/width_heuristics)
max_width = 120
struct_lit_width = 50

use_field_init_shorthand = true

imports_granularity = "Module"
group_imports = "StdExternalCrate"
imports_layout = "HorizontalVertical"
